import React from "react";
import {
  ArchiveBoxIcon,
  ArrowDownIcon,
  ArrowDownTrayIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BeakerIcon,
  BellIcon,
  BoltIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  CpuChipIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DocumentIcon,
  DocumentTextIcon,
  EllipsisHorizontalIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FolderIcon,
  InformationCircleIcon,
  ListBulletIcon,
  LockClosedIcon,
  PaperAirplaneIcon,
  PencilIcon,
  PlusIcon,
  PuzzlePieceIcon,
  ShareIcon,
  ServerStackIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  Squares2X2Icon,
  TableCellsIcon,
  TrashIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserPlusIcon,
  VideoCameraIcon,
  WrenchScrewdriverIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";

const iconMap: Record<string, React.FC<React.SVGProps<SVGSVGElement>>> = {
  "alert": ExclamationTriangleIcon,
  "angle-down": ChevronDownIcon,
  "angle-left": ChevronLeftIcon,
  "angle-right": ChevronRightIcon,
  "angle-up": ChevronUpIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-up": ArrowUpIcon,
  "bell": BellIcon,
  "bolt": BoltIcon,
  "box": ArchiveBoxIcon,
  "box-cube": CubeIcon,
  "box-line": ArchiveBoxIcon,
  "calendar": CalendarDaysIcon,
  "chat": ChatBubbleLeftRightIcon,
  "check-circle": CheckCircleIcon,
  "check-line": CheckIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "close": XMarkIcon,
  "close-line": XMarkIcon,
  "copy": ClipboardDocumentIcon,
  "docs": DocumentTextIcon,
  "dollar-line": CurrencyDollarIcon,
  "download": ArrowDownTrayIcon,
  "envelope": EnvelopeIcon,
  "error": ExclamationCircleIcon,
  "eye": EyeIcon,
  "eye-close": EyeSlashIcon,
  "file": DocumentIcon,
  "folder": FolderIcon,
  "grid": Squares2X2Icon,
  "group": UserGroupIcon,
  "horizontal-dots": EllipsisHorizontalIcon,
  "info": InformationCircleIcon,
  "list": ListBulletIcon,
  "lock": LockClosedIcon,
  "mail": EnvelopeIcon,
  "mail-line": EnvelopeIcon,
  "more-dot": EllipsisHorizontalIcon,
  "page": DocumentIcon,
  "paper-plane": PaperAirplaneIcon,
  "pencil": PencilIcon,
  "pie-chart": ChartPieIcon,
  "plug-in": PuzzlePieceIcon,
  "plus": PlusIcon,
  "shooting-star": SparklesIcon,
  "sparkles": SparklesIcon,
  "table": TableCellsIcon,
  "task": ClipboardDocumentListIcon,
  "test-chat": ChatBubbleOvalLeftEllipsisIcon,
  "time": ClockIcon,
  "trash": TrashIcon,
  "user": UserIcon,
  "user-circle": UserCircleIcon,
  "user-line": UserIcon,
  "user-plus": UserPlusIcon,
  "videos": VideoCameraIcon,
  "wrench": WrenchScrewdriverIcon,
  "chart-bar": ChartBarIcon,
  "cpu": CpuChipIcon,
  "beaker": BeakerIcon,
  "share": ShareIcon,
  "server-stack": ServerStackIcon,
  "shield-check": ShieldCheckIcon,
};

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
  className?: string;
}

const Icon: React.FC<IconProps> = ({ name, className, ...props }) => {
  const IconComponent = iconMap[name];
  if (!IconComponent) return null;
  return <IconComponent className={className} {...props} />;
};

export default Icon;

// Named exports for backward compatibility
export {
  ArchiveBoxIcon as BoxIcon,
  ArchiveBoxIcon as BoxIconLine,
  ArrowDownIcon,
  ArrowDownTrayIcon as DownloadIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BellIcon,
  BoltIcon,
  CalendarDaysIcon as CalenderIcon,
  ChartPieIcon as PieChartIcon,
  ChatBubbleLeftRightIcon as ChatIcon,
  CheckCircleIcon,
  CheckIcon as CheckLineIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronUpIcon,
  ClipboardDocumentIcon as CopyIcon,
  ClipboardDocumentListIcon as TaskIcon,
  ClockIcon as TimeIcon,
  CubeIcon as BoxCubeIcon,
  CurrencyDollarIcon as DollarLineIcon,
  DocumentIcon as FileIcon,
  DocumentIcon as PageIcon,
  DocumentTextIcon as DocsIcon,
  EllipsisHorizontalIcon as HorizontaLDots,
  EllipsisHorizontalIcon as MoreDotIcon,
  EnvelopeIcon,
  EnvelopeIcon as MailIcon,
  ExclamationCircleIcon as ErrorIcon,
  ExclamationTriangleIcon as AlertIcon,
  EyeIcon,
  EyeSlashIcon as EyeCloseIcon,
  FolderIcon,
  InformationCircleIcon as InfoIcon,
  ListBulletIcon as ListIcon,
  LockClosedIcon as LockIcon,
  PaperAirplaneIcon as PaperPlaneIcon,
  PencilIcon,
  PlusIcon,
  PuzzlePieceIcon as PlugInIcon,
  SparklesIcon as ShootingStarIcon,
  SpeakerWaveIcon as AudioIcon,
  Squares2X2Icon as GridIcon,
  TableCellsIcon as TableIcon,
  TrashIcon as TrashBinIcon,
  UserCircleIcon,
  UserGroupIcon as GroupIcon,
  UserIcon,
  VideoCameraIcon as VideoIcon,
  XMarkIcon as CloseIcon,
  XMarkIcon as CloseLineIcon,
  ChevronDownIcon as AngleDownIcon,
  ChevronUpIcon as AngleUpIcon,
  ChartBarIcon,
  CpuChipIcon,
  BeakerIcon,
  ShareIcon,
  ServerStackIcon,
  ShieldCheckIcon,
  UserPlusIcon,
  WrenchScrewdriverIcon,
  ChatBubbleOvalLeftEllipsisIcon,
};
